// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramDesigner.Infrastructure.Data.Context;

#nullable disable

namespace ProgramDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramDesigner.Domain.LearningProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RootGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RootGroupId")
                        .IsUnique();

                    b.ToTable("LearningPrograms", (string)null);
                });

            modelBuilder.Entity("ProgramDesigner.Domain.ProgramItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("ProgramItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("ProgramItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramItemPrerequisites", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramItemId")
                        .HasColumnType("int");

                    b.HasKey("PrerequisiteId", "ProgramItemId");

                    b.HasIndex("ProgramItemId");

                    b.ToTable("ProgramItemPrerequisites");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Group", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.ProgramItem");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Step", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.ProgramItem");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Step");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.LearningProgram", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.Group", "RootGroup")
                        .WithOne()
                        .HasForeignKey("ProgramDesigner.Domain.LearningProgram", "RootGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RootGroup");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.ProgramItem", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.Group", "ParentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("ProgramItemPrerequisites", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.ProgramItem", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgramDesigner.Domain.ProgramItem", null)
                        .WithMany()
                        .HasForeignKey("ProgramItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Group", b =>
                {
                    b.OwnsOne("ProgramDesigner.Domain.ValueObjects.GroupRule", "Rule", b1 =>
                        {
                            b1.Property<int>("GroupId")
                                .HasColumnType("int");

                            b1.Property<int?>("ChoiceCount")
                                .HasColumnType("int")
                                .HasColumnName("ChoiceCount");

                            b1.Property<int>("RuleType")
                                .HasColumnType("int")
                                .HasColumnName("RuleType");

                            b1.HasKey("GroupId");

                            b1.ToTable("ProgramItems");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.Navigation("Rule")
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramDesigner.Domain.Group", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
