// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramDesigner.DAL.Data.Context;

#nullable disable

namespace ProgramDesigner.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729004619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.LearningProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RootGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RootGroupId");

                    b.ToTable("LearningPrograms", (string)null);
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.ProgramItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("PrerequisiteItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("PrerequisiteItemId");

                    b.ToTable("ProgramItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("ProgramItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.Group", b =>
                {
                    b.HasBaseType("ProgramDesigner.DAL.Data.Models.ProgramItem");

                    b.Property<int?>("ChoiceCount")
                        .HasColumnType("int");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.Step", b =>
                {
                    b.HasBaseType("ProgramDesigner.DAL.Data.Models.ProgramItem");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Step");
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.LearningProgram", b =>
                {
                    b.HasOne("ProgramDesigner.DAL.Data.Models.Group", "RootGroup")
                        .WithMany()
                        .HasForeignKey("RootGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RootGroup");
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.ProgramItem", b =>
                {
                    b.HasOne("ProgramDesigner.DAL.Data.Models.Group", "ParentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProgramDesigner.DAL.Data.Models.ProgramItem", "PrerequisiteItem")
                        .WithMany()
                        .HasForeignKey("PrerequisiteItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");

                    b.Navigation("PrerequisiteItem");
                });

            modelBuilder.Entity("ProgramDesigner.DAL.Data.Models.Group", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
